In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "age": [23, None, 30, None],
    "income": [50000, 55000, None, 62000]
})
df

   id   age   income
0   1  23.0  50000.0
1   2   NaN  55000.0
2   3  30.0      NaN
3   4   NaN  62000.0

In [3]:
clean = (
    df
        .assign(age = lambda x: x.age.fillna(x.age.median()))
        .assign(income = lambda x: x.income.fillna(0))
)

clean

   id   age   income
0   1  23.0  50000.0
1   2  26.5  55000.0
2   3  30.0      0.0
3   4  26.5  62000.0

In [4]:
roll_die = np.random.choice((1, 7), size = 2, replace = False)
print(roll_die)

a = np.arange(0, 6) + 1
die = np.random.choice(a, size = 2, replace = False)
print(die)

[1 7]
[4 2]

In [5]:
np.random.seed(0)
unif = np.random.uniform(2, 4, 1000)
print(unif[:5])

normal = np.random.normal(0, 1, 400)
print(normal[:5])
print(f'Probablity less than equal to 0.5 is: {np.mean(normal >= -0.5)}')

[3.09762701 3.43037873 3.20552675 3.08976637 2.8473096 ]
[-0.10169727  0.01927938  1.84959125 -0.21416666 -0.49901664]
Probablity less than equal to 0.5 is: 0.7175

In [6]:
gamma = np.random.gamma(shape = 3, scale = 10, size = 10000)
print(gamma[:5])
print(f'The mean of this gamma distibution should be shape x scale = {np.mean(gamma)}')
print(f'Probability below the mean value will be: {np.mean(gamma < np.mean(gamma))}')

[63.16936565 33.32334773 29.94173729 11.88365567 68.85462549]
The mean of this gamma distibution should be shape x scale = 29.817532629585656
Probability below the mean value will be: 0.5805

In [7]:
peng = pd.read_csv('penguins.csv')

# using assign for silly shit

peng['bill_ratio'] = peng['bill_length_mm'] / peng['bill_depth_mm']
peng = peng.assign(bill_ratio1 = peng['bill_length_mm'] / peng['bill_depth_mm'])
print(peng[['bill_ratio', 'bill_ratio1']][:5])


# Using np.select

conditions = [
    peng['body_mass_g'].isna(),
    peng['body_mass_g'] < 3500,
    (peng['body_mass_g'] >= 3500) & (peng['body_mass_g'] < 4500),
    peng['body_mass_g'] >= 4500
]

values = ['missing', 'low', 'medium', 'high']

peng['mass_category'] = np.select(conditions, values, default = 'unknown')
print(peng['mass_category'][:5])


peng = peng.assign(
    body_mass_g = lambda df: df.body_mass_g.fillna(df.body_mass_g.mean())
)



peng['mass_category_2'] = np.select(conditions, values, default = 'unknown')
print(peng[['mass_category', 'mass_category_2']][:5])

   bill_ratio  bill_ratio1
0    2.090909     2.090909
1    2.270115     2.270115
2    2.238889     2.238889
3         NaN          NaN
4    1.901554     1.901554
0     medium
1     medium
2        low
3    missing
4        low
Name: mass_category, dtype: object
  mass_category mass_category_2
0        medium          medium
1        medium          medium
2           low             low
3       missing         missing
4           low             low

In [8]:
new_data = peng.groupby('species', as_index = False).agg(
    mean_bill_length = ('bill_length_mm', 'mean'),
    median_bill_depth = ('bill_depth_mm', 'median'),
    n = ('species', 'count')
).sort_values(by = 'n', ascending = False)
print(new_data)

     species  mean_bill_length  median_bill_depth    n
0     Adelie         38.791391              18.40  152
2     Gentoo         47.504878              15.00  124
1  Chinstrap         48.833824              18.45   68

In [9]:
summary = [
    peng
    .dropna(subset = ['bill_length_mm', 'body_mass_g', 'bill_depth_mm'])
    .assign(bill_ratio = lambda df: df['bill_length_mm'] / df['bill_depth_mm'])
    .groupby('species', as_index = False)
    .agg(mean_bill_length = ('bill_length_mm', 'mean'), median_bill_depth = ('bill_depth_mm', 'median'), count = ('species', 'count'))
    .sort_values(by = 'count', ascending=False)
]   
print(summary)

[     species  mean_bill_length  median_bill_depth  count
0     Adelie         38.791391              18.40    151
2     Gentoo         47.504878              15.00    123
1  Chinstrap         48.833824              18.45     68]

In [10]:

df = pd.DataFrame({
    "id": [1, 2, 3],
    "math": [80, 85, 90],
    "english": [70, 78, 88]
})



useless_long = pd.melt(df)
print(useless_long)

healthy_long = df.melt(
    id_vars = 'id',
    value_vars= ['math', 'english'],
    var_name = 'subject',
    value_name = 'score'
)
print("=" * 50)
print(healthy_long)

  variable  value
0       id      1
1       id      2
2       id      3
3     math     80
4     math     85
5     math     90
6  english     70
7  english     78
8  english     88
==================================================
   id  subject  score
0   1     math     80
1   2     math     85
2   3     math     90
3   1  english     70
4   2  english     78
5   3  english     88

In [11]:
wider = healthy_long.pivot(
    index = 'id',
    columns = 'subject',
    values = 'score'
).reset_index(inplace = False)
print(wider)

subject  id  english  math
0         1       70    80
1         2       78    85
2         3       88    90

In [12]:
df = pd.DataFrame({
    "name": ["Md Rasel,Biswas", "Sara,Khan", "John,Doe"]
})


print([x.split(',')[0] for x in df['name']])

['Md Rasel', 'Sara', 'John']

In [27]:
students = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]
})
scores = pd.DataFrame({
    "id": [2, 3, 3, 5],
    "score": [80, 90, 85, 70]
})



inner_join = pd.merge(left = students, right = scores, how =  'inner', on  = 'id')
print(inner_join)


full_join = pd.merge(left = students, right = scores, how = 'outer', on  = 'id')
print(full_join)

left_join = students.merge(scores, how = 'left', on = 'id')
print(left_join)

right_join = students.merge(scores, how = 'right', left_on = 'id', right_on = 'id', suffixes = ('_sc', '_st'))
print(right_join)

   id name  score
0   2    B     80
1   3    C     90
2   3    C     85
   id name  score
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0
3   3    C   85.0
4   4    D    NaN
5   5  NaN   70.0
   id name  score
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0
3   3    C   85.0
4   4    D    NaN
   id name  score
0   2    B     80
1   3    C     90
2   3    C     85
3   5  NaN     70

In [30]:
bins = [0, 3500, 4500, np.inf]
labels = ['low', 'medium', 'high']
peng['mass_bin'] = pd.cut(peng['body_mass_g'], bins = bins, labels = labels)
print(peng['mass_bin'][:5])

0    medium
1    medium
2       low
3    medium
4       low
Name: mass_bin, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']